version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: voting_app_backend
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --reload
    networks:
      - voting_app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voting_app_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    networks:
      - voting_app_network

networks:
  voting_app_network:
    driver: bridge
