name: Build Python documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Generate API docs
        run: sphinx-apidoc -o docs project

      - name: Generate documentation
        run: sphinx-build -b html docs docs/_build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build

      - name: Deploy
        uses: actions/deploy-pages@v4
